version: '3.8'
services:
  sharp_theory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"  
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
